import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="bg-black flex justify-center">
                <div className="w-[800px] mt-10 flex justify-center
                 text-slate-50 border-white tracking-wide bg-slate-900 p-8">
                    {children}
                </div>
            </body>
        </html>
    );
}
